server:
  port: ${PORT:8080}
app:
  hello_sign:
     api_key: ${HELLO_SIGN_API_KEY:not set}
     template_id: ${HELLO_SIGN_TEMPLATE_ID:not set}
     webhook_url: https://hello-sign-sample.herokuapp.com/sign/webhook